server:
  port: 8002

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ymk;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: testProd
    password: testProd
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      maximum-pool-size: 500
      minimumIdle: 9
      idleTimeout: 10000
      connection-timeout: 10000
      validation-timeout: 10000
      maxLifetime: 30000
#      connection-test-query: SELECT 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  h2:
    console:
      enabled: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    
  redis:
    host: domain.com
    port: 6379
    password: password
    
jwt:
  tokens:
    - group: AccessToken
      secretKey: acc_ess_tok_ens_ecr_et
      validity: 600000  # 10분 (ms)
    - group: RefreshToken
      secretKey: ref_res_hto_ken_sec_ret
      validity: 259200000  # 3일 (ms)

