server:
  servlet:
    context-path: /template
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    connection-timeout: 120000

logging:
  level:
    root: info
    org.springframework.security.web.FilterChainProxy: debug
    org.hibernate.type.descriptor.sql: trace

spring:
  profiles:
    active: local  # 사용할 프로파일 지정

  devtools:
    livereload:
      enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: false
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        cache:
          usesecondlevelcache: true
          usequerycache: false
          region:
            factoryclass: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        generatestatistics: true


jwt:
  tokens:
    - group: AccessToken
      secretKey: acc_ess_tok_ens_ecr_et
      validity: 600000  # 10분 (ms)
    - group: RefreshToken
      secretKey: ref_res_hto_ken_sec_ret
      validity: 259200000  # 3일 (ms)
