server:
  port: 8001

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/mydb?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      username: WRITE_USER
      password: write_password
      type: com.zaxxer.hikari.HikariDataSource
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/mydb?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      username: READ_USER
      password: read_password
      type: com.zaxxer.hikari.HikariDataSource

    hikari:
      maximum-pool-size: 50
      minimumIdle: 5
      idleTimeout: 10000
      connection-timeout: 10000
      validation-timeout: 5000
      maxLifetime: 30000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  redis:
    host: localhost
    port: 6380

jwt:
  tokens:
    - group: AccessToken
      secretKey: acc_ess_tok_ens_ecr_et
      validity: 1800000  # 30분 (ms)
    - group: RefreshToken
      secretKey: ref_res_hto_ken_sec_ret
      validity: 259200000  # 3일 (ms)
