server:
  port: 8000

spring:
  config:
    activate:
      on-profile: mac

  datasource:
    admin:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:ymk;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:data.sql'
      username: sa
      password: 
      type: com.zaxxer.hikari.HikariDataSource

    write:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:ymk;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
      username: sa # 쓰기 전용 계정
      password: 
      type: com.zaxxer.hikari.HikariDataSource
    read:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:ymk;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
      username: sa # 읽기 전용 계정
      password: 
      type: com.zaxxer.hikari.HikariDataSource

    hikari:
      maximum-pool-size: 500
      minimumIdle: 9
      idleTimeout: 10000
      connection-timeout: 10000
      validation-timeout: 10000
      maxLifetime: 30000
#      connection-test-query: SELECT 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  
  redis:
    host: localhost
    port: 6380
    
jwt:
  tokens:
    - group: AccessToken
      secretKey: access_token_secret_key_for_jwt_sha_256_bit
      validity: 180000000  # 30분 (ms)
    - group: RefreshToken
      secretKey: refresh_token_secret_key_for_jwt_sha_256_bit
      validity: 259200000  # 3일 (ms)